### ISSUE TITLE
Error when trying to add more than 4 assets to the programm code

### ISSUE THREAD

**Issue by austriachainone** [DocCryptastic/crypto_simulations#1]
Dear developer,

I am having an issue trying to add more than one asset pair into the code of you various python files. Are you so kind to let me know what other changes I have to execute in order to be able to optimize a portfolio consisting of more than 4 assets. 

Thank you very much!
Best regards

**Comment by jS1ngle** [comment]
Hi, I resolved this issue by generalizing the code and testing it with multiple assets.
